### ISSUE TITLE
Transplant solver from NESO

### ISSUE THREAD

**Issue by oparry-ukaea** [ExCALIBUR-NEPTUNE/NESO-hw-impurity-transport#1]
Copy-paste contents of `solvers/hw-impurity-transport` from [temporary NESO branch](https://github.com/ExCALIBUR-NEPTUNE/NESO/tree/tmp/hw-impurities-transport) into this repo.

**Comment by jwscook** [comment]
This is dependent on https://github.com/ExCALIBUR-NEPTUNE/NESO/pull/225
