### ISSUE TITLE
NESO-HW-Impurity-Transport

### ISSUE THREAD

**Issue by jwscook** [ExCALIBUR-NEPTUNE/NESO-hw-impurity-transport#6]
Chris Ridgers wants a HW app in 3D that tracks particles passively according to the applied magnetic field and then dynamic potential. We need:
 - A repo for NESO-HW-Impurity-Transport
 - To call NESO as a library from this repo
 - To add particle capability to the 2D and 3D HW system using the gradient of the HW potential as the electric field. The B field is a constant (make it possible to turn off the B field off in particle push).
 - This is concentrating on slab geometry at first.

**Comment by jwscook** [comment]
This issue has been converted from an Item in the 3D3V Turbulence and neutrals Project board.

**Comment by jwscook** [comment]
The details are captured in https://github.com/orgs/ExCALIBUR-NEPTUNE/projects/3

**Comment by oparry-ukaea** [comment]
Think all of these requirements are satisfied now? Shall I close?
